add mypy to github actions
mquat/cafeLab pull request #11
Opened 2023-04-16 08:56 UTC by mquat

### PR 목적
- mypy github actions에 추가

### 작업 내용
- mypy install & run 을 github actions에 추가하여 type hint 체크가 되도록 함

### 기타 코멘트

2023-04-17 15:12 UTC, mquat commented
@jacob-f-lab 우선 디렉토리 중 `crud` 만 적용했고, `--ignore-missing-imports` flag를 추가했는데 이유는 아래와 같습니다 
1. flag를 적용하지 않으면 계속 sqlalchemy/sqlalchemy.orm/pydantic 등을 찾을 수가 없다는 에러가 뜨는데, 위 방법 말고는 해결 방법을 찾지 못해 우선 ignore 처리했습니다 ㅠ 
 -> ([공식문서](https://mypy.readthedocs.io/en/stable/running_mypy.html#cannot-find-implementation-or-library-stub)를 보면 1) import하려는 라이브러리 오타 확인 -> 확인 완료, 2) 가상환경 내부에서 실행하는게 맞는지 확인 -> 확인 완료, 3) config file에 `MYPYPATH` 관련 설정 -> 이해가 안되고 설정을 어디에 하라는건지도 잘.. 모르겠네요 ;;) 
 -> 혹시 다른 더 적절한 설정이 있다면, 힌트 주시면 감사하겠습니다
<img width="765" alt="image" src="https://user-images.githubusercontent.com/97735091/232526949-eea819eb-6eaf-440d-8fa4-7a2afa7531e5.png">

2. 전체 디렉토리를 적용하면 `utils/config.py` 에 에러가 뜨는데, 아래 에러 메세지에서 언급하는 mysql_username, mysql_password 등은 타입 힌트를 적용한게 없는데 타입 힌트 불일치라고 하여 ...ㅠ 우선 `crud` 만 mypy를 적용했습니다. 
  -> 아래 에러 메세지대로, `utils/config.py` 의 타입 힌트를 Optional[str]로 바꾸면 에러가 사라지긴 합니다 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/97735091/232526738-bb0c2b7c-d235-4eb9-8226-182431ef7bb2.png">

2023-04-17 15:16 UTC, mquat commented
그리고, 이유를 모르겠는데 pip list/pip freeze를 하면 자꾸 다르게 나와서.. 여러번 해당 명령어를 쳐본 결과를 다시 requirements.txt에 반영했습니다. 참고 부탁 드립니다 (아마도 conda가 제대로 켜져 있지 않은 상태에서 pip list/freeze를 쳤었다거나... 그런 이유가 아닐까 추측합니다)

2023-04-19 05:27 UTC, jacob-f-lab commented
> @jacob-f-lab 우선 디렉토리 중 `crud` 만 적용했고, `--ignore-missing-imports` flag를 추가했는데 이유는 아래와 같습니다
> 
> 1. flag를 적용하지 않으면 계속 sqlalchemy/sqlalchemy.orm/pydantic 등을 찾을 수가 없다는 에러가 뜨는데, 위 방법 말고는 해결 방법을 찾지 못해 우선 ignore 처리했습니다 ㅠ
>    -> ([공식문서](https://mypy.readthedocs.io/en/stable/running_mypy.html#cannot-find-implementation-or-library-stub)를 보면 1) import하려는 라이브러리 오타 확인 -> 확인 완료, 2) 가상환경 내부에서 실행하는게 맞는지 확인 -> 확인 완료, 3) config file에 `MYPYPATH` 관련 설정 -> 이해가 안되고 설정을 어디에 하라는건지도 잘.. 모르겠네요 ;;)
>    -> 혹시 다른 더 적절한 설정이 있다면, 힌트 주시면 감사하겠습니다
> 
> <img alt="image" width="765" src="https://user-images.githubusercontent.com/97735091/232526949-eea819eb-6eaf-440d-8fa4-7a2afa7531e5.png">
> 
> 2. 전체 디렉토리를 적용하면 `utils/config.py` 에 에러가 뜨는데, 아래 에러 메세지에서 언급하는 mysql_username, mysql_password 등은 타입 힌트를 적용한게 없는데 타입 힌트 불일치라고 하여 ...ㅠ 우선 `crud` 만 mypy를 적용했습니다.
>    -> 아래 에러 메세지대로, `utils/config.py` 의 타입 힌트를 Optional[str]로 바꾸면 에러가 사라지긴 합니다
> 
> <img alt="image" width="887" src="https://user-images.githubusercontent.com/97735091/232526738-bb0c2b7c-d235-4eb9-8226-182431ef7bb2.png">

안녕하세요.
1 같은 경우에는 해당 모듈들이 type 정보를 제공하지 않아서 생기는 문제로 https://pypi.org/project/sqlalchemy-stubs/ 와 같은 별도의 모듈을 이용해서 해결할 수 있습니다. 해당 모듈들의 타입보다는 직접 작성하는 코드 내에서 타입 정보를 사용하는것이 목적이기 때문에 지금은 --ignore-missing-imports 옵션을 주신게 더 좋은 해결책인것 같습니다.
2 는 os.getenv 가 Optional[str]을 반환해서 (str 또는 None일수 있습니다) 생긴 문제입니다. mysql_username : Optional[str] 과 같이 바꿔주시면 됩니다.

2023-04-19 05:27 UTC, jacob-f-lab commented
@mquat 네 conda 환경에 진입하지 않은 상태에서 설치를 하거나 한 것 같네요.

2023-04-19 05:28 UTC, jacob-f-lab requested changes
utils/config.py 의 타입 정보 수정해주세요

2023-04-26 06:38 UTC, jacob-f-lab approved these changes

2023-04-26 11:28 UTC, merged