add test code for user signup
mquat/cafeLab pull request #12
Opened 2023-04-19 15:57 UTC by mquat

### PR 목적
- User생성 테스트 코드 작성
<img width="886" alt="image" src="https://user-images.githubusercontent.com/97735091/233132590-814ab5dd-ce73-4b95-9bb1-9b87763f9ece.png">

### 작업 내용
- User 생성 테스트 코드
- 중복 계정/invalid 계정(정규식 위반 - username/password/email) 테스트 코드

### 기타 코멘트
- 원래 http method가 `delete` 인 케이스의 테스트 코드는 작성하지 않는 것일까요? 
  `delete`인 경우, `assert response.status_code == 204` 가 불가능하여 여쭤봅니다. 
   (그리고 삭제 관련 테스트코드도 찾아봤는데 나오지 않아서 혹시나 싶어서 여쭤봅니다)

2023-04-26 18:18 UTC, jacob-f-lab commented
> 원래 http method가 delete 인 케이스의 테스트 코드는 작성하지 않는 것일까요?
delete인 경우, assert response.status_code == 204 가 불가능하여 여쭤봅니다.
(그리고 삭제 관련 테스트코드도 찾아봤는데 나오지 않아서 혹시나 싶어서 여쭤봅니다)

https://github.com/mquat/cafeLab/blob/521f760697646c27ef9b721fd203528d9201cebb/routers/user.py#L44 요 라인 보시면 return None 을 하고 있는데 이 경우에는 HTTP 200 으로 리스폰스가 가게 됩니다.

HTTP 204를 보내주고 싶으시다면 https://fastapi.tiangolo.com/tutorial/response-status-code/ 요 문서를 읽어보시면 좋을것 같습니다

2023-04-26 18:18 UTC, jacob-f-lab requested changes
delete 관련 코드 추가해주세요 🙇

2023-04-27 16:51 UTC, mquat commented
@jacob-f-lab 일단 작성은 했는데, 몇 가지 고민되는 부분 있어 추가로 코멘트 드립니다 ..  😂
1. User delete API는 `status_code=204` 를 리턴하게끔 작성했고, 실제로 postman에서 테스트를 해보면 204를 반환합니다. 그래서 200을 반환한다는 피드백을 100% 이해하지 못했습니다 ㅠ
2. 일단은 test 함수 전에 test용으로 생성한 User 계정의 id에 임의 값을 주고, `{'user_id': id값}` 을 보내서 제대로 작성하는 경우 return이 None인지를 확인하도록 작성했습니다. 
3. 하지만 역시나 좋은 코드가 아닌 것 같아...(status code를 assert문에 못 넣는 것도 뭔가 찜찜하고요...)  대안으로 생각해둔 코드는 아래와 같습니다. 한번 보시고 피드백 부탁 드립니다. 
- http method를 patch로 변경해 이에 맞게 작성

`

    #현재 수정한 코드
    new_user_info['id'] = 1000
    def test_delete_user():
    response = client.delete(
        "/user/delete",
        json = {'user_id': new_user_info['id']}
    )

    assert '' in response.text


    #대안 코드 
    new_user_info['id'] = 1000
    def test_delete_user():
        response = client.patch(
            "/user/delete",
            json = {'user_id': new_user_info['id']}
        )

    assert response.status_code == 204
    assert '' in response.text
`

2023-05-10 13:57 UTC, mquat commented
@jacob-f-lab 파일을 옮겨서 해도 안되서 우선 아래와 같이 수정해봤습니다..🥲 
- `response = client.delete()` 인 경우 `response.status_code` 자체가 support안되는 것 같아, 관련 [github issue](https://github.com/tiangolo/fastapi/issues/5649#issuecomment-1316958036)
- 위 링크를 참고해서 `response = client.request()` 로 바꿨더니 `response.status_code` 가 작동합니다

2023-05-11 23:51 UTC, jacob-f-lab approved these changes

2023-05-13 23:55 UTC, merged