add user login function with token
mquat/cafeLab pull request #14
Opened 2023-04-26 13:26 UTC by mquat

### PR 목적
- User 로그인 기능 추가 

### 작업 내용
- 유효한 id 확인 후 password verify
- id 와 password 모두 유효한 경우 token 발행해서 전달
<img width="540" alt="image" src="https://user-images.githubusercontent.com/97735091/234589647-97abe7fc-eabe-4e4b-a849-d193d1bb29fa.png">

### 기타 코멘트

2023-04-26 18:23 UTC, jacob-f-lab requested changes

2023-04-26 18:23 UTC, jacob-f-lab commented on crud/user.py
> +        return False
함수의 리턴 타입은 한가지로 통일하는 편이 좋습니다. 이 경우에는 적절한 유저 레코드를 찾지 못했다는 의미로 None을 반환해주거나 exception을 선언할 수 있습니다. 두가지 모두 장단점이 있는데 아래 글을 읽어보시면 좋을 것 같습니다.
* https://medium.com/swlh/we-need-to-stop-using-null-heres-why-c56ff3ac72dd (Tracking Nulls Leads to Sloppy Code 섹션)
* https://stackoverflow.com/questions/16138232/is-it-a-good-practice-to-use-try-except-else-in-python#:~:text=Python%20doesn't%20subscribe%20to,%2C%20and%20in%20fact%2C%20encouraged.

2023-04-26 18:23 UTC, jacob-f-lab commented on utils/auth.py
> +db = Depends(get_db)
👍

2023-04-26 18:23 UTC, jacob-f-lab commented on utils/config.py
> +    algorithm      : Optional[str] = os.getenv("ALGORITHM")
algorithm은 비밀키로 관리될 이유가 없어보입니다. 혹시 환경변수로 관리하려고 하신 이유가 있으실까요?

2023-04-30 16:23 UTC, mquat commented on crud/user.py
> +        return False
article 감사합니다..! 첫 번째 article에서 소개한 대로 None을 사용하면 계속 트래킹해야 한다는 단점이 있으나, 해당 함수는 찾고자 하는 User 혹은 None(User 없음)을 반환해 로그인 가능 유무를 확인하는데만 쓰이므로 위의 단점이 발생할 가능성이 높지 않아 None을 사용하는 것으로 수정했습니다.

2023-04-30 16:32 UTC, mquat commented
@jacob-f-lab 피드백 반영 및 추가 수정하였습니다, 확인 부탁 드립니다! 
1. JWT의 알고리즘 정보는 `.env` 에서 제거 
2. login info validation 함수의 return 값은 가입한 user 정보 or None으로 수정 
3. 반환 받은 user (type: sqlalchemy.engine.row)를 dict로 변환하는 부분 수정 
     -> 다시 테스트해보니 제대로 dict로 반환되지 않는 에러 발생 
     -> sqlalchemy 버전 1.4 이상부터는 `row._mapping` -> `dict()` 사용을 통해 dict로 변환할 수 있어 해당 방법 적용 
     -> 해당 변수명도 `current_user_as_dict` 로 변경

2023-05-05 21:40 UTC, jacob-f-lab requested changes

2023-05-05 21:40 UTC, jacob-f-lab commented on routers/user.py
> +    token = create_access_token(current_user_as_dict)
이 경우 current_user_as_dict 가 password도 담고 있을것 같습니다. password가 노출되지 않아야 할것 같습니다.

2023-05-05 21:40 UTC, jacob-f-lab commented on routers/user.py
> +    current_user_as_dict = dict(current_user._mapping)
user 를 dict로 변환한 이유가 있을까요?

2023-05-08 15:34 UTC, mquat commented
@jacob-f-lab 주신 피드백 반영하여 수정했습니다, 확인 부탁 드립니다! 
1. token payload 변경: 민감정보를 담을 경우 보안 위험이 있다는 사실을 간과했네요, payload에는 user id가 담기도록 변경했습니다.
2. user를 dict로 변환한 문제: db.query.first()로 읽어온 데이터는 sqlalchemy.row.Row 형태라서 dict로 변환해야만 `user['passowrd']` 와 같이 읽을 수 있을거라고 생각했는데, 변환하지 않고도 가능하여 해당 부분은 삭제했습니다.

2023-05-08 19:12 UTC, jacob-f-lab approved these changes

2023-05-09 07:22 UTC, merged