add user logout function
mquat/cafeLab pull request #15
Opened 2023-05-09 15:08 UTC by mquat

### PR 목적
- User 로그아웃 기능 추가

### 작업 내용
- config에 redis 정보 추가
- 로그인한 User의 토큰으로 유효한 계정임을 확인 
- 토큰은 redis 에 저장 & 일정 기간 지나면 파기 (아래 캡처는 로그아웃 후, 해당 토큰이 redis에 `token:'signed_out'` 형태로 저장된 것)
<img width="600" alt="image" src="https://github.com/mquat/cafeLab/assets/97735091/034a59d0-8a48-48de-b557-da04376b852a">

### 기타 코멘트
- redis관련 type hint 검사 (mypy) 에러를 없애기 위해 `main.yml` 에 `pip install types-redis` 를 추가했습니다.

2023-05-09 19:46 UTC, jacob-f-lab requested changes

2023-05-09 19:46 UTC, jacob-f-lab commented on utils/auth.py
> +        redis.setex(name=authorization, time=(expired_date-current_date), value='signed_out')
이 함수 안에서 redis로 어떤 기능을 구현하고자 했는지 이해하기가 어렵습니다. 조금 더 자세하게 설명해주실 수 있을까요? redis에 JWT 를 키로 저장하는것은 어떤 장점이 있을까요? (일종의 deny-list 를 만들고자 한것 같은데 맞을까요?)

2023-05-10 16:15 UTC, mquat commented
@jacob-f-lab `get_login_user` 를 각 역할을 기준으로 쪼갰는데 한번 확인 부탁 드립니다!

2023-05-15 13:55 UTC, mquat commented
@jacob-f-lab 그리고 추가로, user login에서 유효한 user의 password 와 id를 읽는데 다시 에러가 발생하는 것을 발견해, 아래와 같이 수정했습니다 (이전 PR에서 resultproxy 기반으로 dict-like access 방식으로 작업했던 부분입니다) 
- `current_user['password']` -> `current_user.password` 로 변경
- `current_user['id']` -> `current_user.id`로 변경

2023-05-25 22:03 UTC, jacob-f-lab approved these changes

2023-05-26 13:25 UTC, merged