add cafe info crawling
mquat/cafeLab pull request #21
Opened 2023-06-16 15:40 UTC by mquat

### PR 목적
- 카페 정보 크롤링(DB 업데이트)
<img width="750" alt="image" src="https://github.com/mquat/cafeLab/assets/97735091/a47c3f49-7f0d-48fc-b8ce-af95159863b5">

### 작업 내용
- 카카오 로컬 API를 이용해 주요 정보 DB에 저장
- 만약 이미 DB에 있는 카페일 경우 pass

### 기타 코멘트
- 부대시설 크롤링은 추후 추가할 예정입니다
- 카페 정보 업데이트는 cron tab을 통해 구현할 예정입니다

2023-06-23 13:39 UTC, jacob-f-lab requested changes

2023-06-23 13:39 UTC, jacob-f-lab commented on scheduler/cafe_info.py
> +    result = requests.get(url, headers=header).json()
request가 실패할 경우 (200 이외의 코드가 반환될 경우)에 대한 처리가 필요할것 같습니다

2023-06-23 13:39 UTC, jacob-f-lab commented on scheduler/cafe_info.py
> +        for new_cafe in kakao_cafe_list:
23-28번 줄 에서 여집합 연산을 set으로 할수 있을것 같습니다.
요건 필수는 아니고 코드를 더 간결하게 만드는 데 의미가 있습니다.
https://stackoverflow.com/questions/3942303/how-does-a-python-set-check-if-two-objects-are-equal-what-methods-does-an-o

2023-06-25 14:33 UTC, mquat commented on scheduler/cafe_info.py
> +        for new_cafe in kakao_cafe_list:
@jacob-f-lab 사실 처음 작성할 때 set연산을 고려해보긴 했는데요, 다시 살펴봤으나 여전히 적용하기 어려운 부분이 있다고 생각되어 수정하지 않았습니다.

코드의 주요 내용은 현재 DB에 있는 카페 목록(`db_cafe_list`) 과 카카오로 불러온 카페 목록(`kakao_cafe_list`)을 비교하는 것인데, 
1) DB 에서 갖고온 데이터와 카카오에서 갖고온 데이터 형태나 내용이 같지 않고, 
2) 결국 set연산이 가능하도록 카페명만 뽑아서 연산한 후 > 남은 카페이름 list를 갖고 다시 `kakao_cafe_list` 를 방문 > 카페 전체 정보를 갖고와 DB에 저장해야 할 것 같습니다. 그래서 결과적으로는 아쉽게도 코드 간결성 정도가 크게 나아지지 않을 것 같은데, 한번 확인 부탁 드립니다~!    
```  
    ...
    ...
    new_cafe_list = set()
    
    #카카오 목록에서 카페명만 뽑아서 new_cafe_list에 넣는다
    for new_cafe in kakao_cafe_list:
        new_cafe_list.add((new_cafe['place_name'],))
    
    #여집합 연산을 통해 새로 추가할 카페명만 남긴다
    new_cafe_list = new_cafe_list - db_cafe_list

    #이후에 다시 kako_cafe_list를 방문해 new_cafe_list에 있는 카페명의 전체 카페 정보를 갖고와 DB에 저장한다
    #(for문 등 사용해서..)
    ...
```

2023-06-27 16:45 UTC, jacob-f-lab commented on scheduler/cafe_info.py
> +        for new_cafe in kakao_cafe_list:
안녕하세요! 제 의도는 아래와 같은 방식으로 문제를 해결하는 것이었습니다.
```
class CafeElement:
  kakao_repr = None
  name = None

  def __init__(self, name, kakao_repr):
    self.name = name
    self.kakao_repr = kakao_repr

  def __eq__(self, other):
    return self.__hash__() == other.__hash__()

  def __hash__(self):
    return self.name

  cafe_set = set([CafeElement(c['place_name'], c) for c in new_cafe])
  // db_cafe_set 에도 CafeElement를 원소로 집어넣는다
  cafe_set -= db_cafe_set

  for c in cafe_list:
    // 여기서 c.kakao_repr 로 카페 정보에 접근
```

2023-06-27 17:14 UTC, jacob-f-lab commented on scheduler/cafe_info.py
> +        for new_cafe in kakao_cafe_list:
하지만 주된 의도는 코드를 더 읽기 쉽게 만들기 / 개별 기능을 함수로 쪼개기 / Set의 내부 동작 알아보기 등이었기 때문에 크게 중요하지는 않은 것 같네요!

2023-06-28 13:43 UTC, mquat commented on scheduler/cafe_info.py
> +        for new_cafe in kakao_cafe_list:
@jacob-f-lab 아 이런 접근방법으로 활용할 수 있군요 .. 힌트로 주셨던 스택오버플로우의 내용을 제가 100% 이해 못해서 활용을 못했습니다 ㅠ (set의 원리가 이렇다 하는 reference로만 이해했던 것 같네요..) 그런데 지금 설명 주신 방법으로도 따로 한번 해보고 싶어서, 일단 현재 코드는 이대로 진행하고 위 방법대로도 추후에 한번 작성해보겠습니다. 감사합니다

2023-06-28 13:45 UTC, merged