Feature/user signup
mquat/cafeLab pull request #8
Opened 2023-04-09 12:41 UTC by mquat

### PR 목적
- User 생성 (회원가입) 기능 추가 

### 작업 내용
- User 생성 및 DB 데이터 추가 
- validation: username/password/email 정규식 적용
- password는 hashing 하여 저장
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/97735091/230773021-6184c264-6148-4c40-a5ce-48cb99010094.png">

### 기타 코멘트

2023-04-12 04:41 UTC, jacob-f-lab requested changes

2023-04-12 04:41 UTC, jacob-f-lab commented on tests/initial_test.py
> +
파일 끝에 개행문자는 하나만 있어야 합니다.

2023-04-12 04:41 UTC, jacob-f-lab commented on schemas/user.py
> +    user_type = 'user'
Enum으로 처리할 수 있을까요?

2023-04-12 04:41 UTC, jacob-f-lab commented on routers/user.py
> +    db: Session = Depends(get_db)
Session은 view function 밖으로 뺄수 있을 것 같습니다

2023-04-12 04:41 UTC, jacob-f-lab commented on routers/user.py
> +    duplicate_user = get_duplicate_user(signup_info, db)
Duplicate user가 있는지 여부로 boolean을 리턴하도록 하면 어떨까요? 사용하지 않을 값을 리턴해주는건 추후에 함수를 오용하기 쉬울 것 같습니다.

2023-04-12 04:41 UTC, jacob-f-lab commented on routers/user.py
> +        signup_info.password = get_password_hash(signup_info.password)
In place로 변경하는것 보다 인자를 변경한 새 객체를 리턴해주는 함수를 만드는 편이 추적하기 쉬울 것 같습니다. 이건 제안이고 필수는 아닙니다.

2023-04-12 15:12 UTC, mquat commented on routers/user.py
> +        signup_info.password = get_password_hash(signup_info.password)
함수 추적의 측면에서 말씀하신 방법이 더 좋은 것 같아 수정했습니다. 사실 처음 코드와 같이 작성했던 이유는, 별도의 객체에 담는 것이 메모리 사용을 최소화할 수 있을 것 같다는 생각이었는데 멘토링 때 이 부분 한번 다시 여쭤보고 싶긴 하네요... :) !

2023-04-12 15:15 UTC, mquat commented on routers/user.py
> +    db: Session = Depends(get_db)
`Depends(get_db)` 는 기본적으로 모든 request마다 포함되는 것이니, 함수마다 이를 계속 작성하는 것보다는 따로 객체에 담아서 사용하라는 의미가 맞을까요? 우선 이렇게 수정했는데 한번 확인해주시면 감사하겠습니다.

2023-04-12 15:16 UTC, mquat commented
@jacob-f-lab 피드백 반영한 PR 올렸습니다~! 그런데 그 중 아래 피드백은 확인 부탁 드립니다. 
- Session은 view function 밖으로 뺄수 있을 것 같습니다
   -> `Depends(get_db)` 는 기본적으로 모든 request마다 포함되는 것이니, 함수마다 이를 계속 작성하는 것보다는 따로 객체에 담아서 사용하라는 의미가 맞을까요? 우선 이렇게 수정했는데 한번 확인해주시면 감사하겠습니다.

2023-04-14 05:00 UTC, jacob-f-lab commented
> @jacob-f-lab 피드백 반영한 PR 올렸습니다~! 그런데 그 중 아래 피드백은 확인 부탁 드립니다.
> 
> * Session은 view function 밖으로 뺄수 있을 것 같습니다
>   -> `Depends(get_db)` 는 기본적으로 모든 request마다 포함되는 것이니, 함수마다 이를 계속 작성하는 것보다는 따로 객체에 담아서 사용하라는 의미가 맞을까요? 우선 이렇게 수정했는데 한번 확인해주시면 감사하겠습니다.

네 제가 의도하고 말씀드린 방향이 맞습니다 :)

2023-04-14 05:00 UTC, jacob-f-lab approved these changes

2023-04-14 06:49 UTC, merged