Feature/user delete
mquat/cafeLab pull request #9
Opened 2023-04-14 15:46 UTC by mquat

### PR 목적
- 회원 삭제 기능

### 작업 내용
- User 삭제 (soft delete, `is_deleted` = True로 변경)
- DB mapping function 변경 (sqlalchemy 버전에 따라 `mapper()` ->`registry.map_imperatively()` 사용)
   -> Error message: "The 'sqlalchemy.orm.mapper()' function is removed as of SQLAlchemy 2.0.  
        Use the 'sqlalchemy.orm.registry.map_imperatively()` method of the ``sqlalchemy.orm.registry`` class 
        to perform classical mapping."
- id=2 계정 삭제한 예시 캡처
<img width="942" alt="스크린샷 2023-04-15 오전 12 42 25" src="https://user-images.githubusercontent.com/97735091/232091355-00a75c27-ce68-4729-94f4-d140f2c49ddb.png">

### 기타 코멘트

2023-04-15 16:22 UTC, jacob-f-lab requested changes

2023-04-15 16:22 UTC, jacob-f-lab commented on crud/user.py
> +    return
타입 힌트랑 함수가 맞지 않는것 같습니다. 마지막에 User를 반환하는 함수라고 써 있는데 None을 리턴하네요.

2023-04-15 16:22 UTC, jacob-f-lab commented on database/models.py
> +mapper_registry.map_imperatively(User, user)
👍

2023-04-16 08:59 UTC, mquat commented on crud/user.py
> +    return
앗 그러네요, None으로 수정했습니다

2023-04-16 09:04 UTC, mquat commented
@jacob-f-lab 아래 내용 추가로 수정했는데 확인 부탁 드립니다! 
- User 삭제의 return type: None으로 수정
- crud/user.py에서 mypy를 돌려본 결과 User 클래스 속성에 `id`가 정의되어 있지 않은 error가 발생 
   -> modeling에서 속성에 `id`와 `joined_at`을 추가하고, schemas에도 이에 맞게 수정

2023-04-19 05:29 UTC, jacob-f-lab commented
> @jacob-f-lab 아래 내용 추가로 수정했는데 확인 부탁 드립니다!
> 
> 1. User 삭제의 return type: None으로 수정
> 2. User 클래스 속성 및 관련 내용 추가 수정
>    -> 1번 내용 수정 후 mypy를 돌려본 결과, crud/user.py의 `delete_user` 에서 `User.id` 가 정의되어 있지 않았다는 에러 추가 발생
>    -> modeling에서 속성에 `id`와 `joined_at`을 추가하고, schemas에도 이에 맞게 수정

👍

2023-04-19 05:29 UTC, jacob-f-lab approved these changes

2023-04-19 10:07 UTC, merged